const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";
const FETCH_CLUBS = "FETCH_CLUBS";
const FETCH_CLUBS_FULFILLED = "FETCH_CLUBS_FULFILLED";
const FETCH_CLUBS_FAILED = "FETCH_CLUBS_FAILED";
const CHANGE_CURRENT_CLUB = "CHANGE_CURRENT_CLUB";
const FETCH_CLUB_TEAMS_FULFILLED = "FETCH_CLUB_TEAMS_FULFILLED";
const FETCH_CLUB_TEAMS_FAILED = "FETCH_CLUB_TEAMS_FAILED";
const CHANGE_CURRENT_TEAM = "CHANGE_CURRENT_TEAM";
const FETCH_TEAM_STANDINGS_FULFILLED = "FETCH_TEAM_STANDINGS_FULFILLED";
const FETCH_TEAM_STANDINGS_FAILED = "FETCH_TEAM_STANDINGS_FAILED";
const FETCH_TEAM_MATCHES_FULFILLED = "FETCH_TEAM_MATCHES_FULFILLED";
const FETCH_TEAM_MATCHES_FAILED = "FETCH_TEAM_MATCHES_FAILED";
const FETCH_TEAM_PLAYERS_FULFILLED = "FETCH_TEAM_PLAYERS_FULFILLED";
const FETCH_TEAM_PLAYERS_FAILED = "FETCH_TEAM_PLAYERS_FAILED";

const BACK_TO_SEARCH = "BACK_TO_SEARCH";

module.exports = {
  CHANGE_SEARCH_VALUE,
  FETCH_CLUBS,
  FETCH_CLUBS_FULFILLED,
  FETCH_CLUBS_FAILED,
  CHANGE_CURRENT_CLUB,
  FETCH_CLUB_TEAMS_FULFILLED,
  FETCH_CLUB_TEAMS_FAILED,
  CHANGE_CURRENT_TEAM,
  BACK_TO_SEARCH,
  FETCH_TEAM_STANDINGS_FULFILLED,
  FETCH_TEAM_STANDINGS_FAILED,
  FETCH_TEAM_MATCHES_FULFILLED,
  FETCH_TEAM_MATCHES_FAILED,
  FETCH_TEAM_PLAYERS_FULFILLED,
  FETCH_TEAM_PLAYERS_FAILED
};
