const CHANGE_DECORATIONS_STEP = "CHANGE_DECORATIONS_STEP";
const ENABLE_DISABLE_SHAPE = "ENABLE_DISABLE_SHAPE";
const SELECT_SHAPE_SUBTYPE = "SELECT_SHAPE_SUBTYPE";
module.exports = {
  CHANGE_DECORATIONS_STEP,
  ENABLE_DISABLE_SHAPE,
  SELECT_SHAPE_SUBTYPE
};
