const CHANGE_API_STEP = "CHANGE_API_STEP";
const CHANGE_SEARCH_CRITERIA = "CHANGE_SEARCH_CRITERIA";
const CHANGE_ITEMS = "CHANGE_ITEMS";
module.exports = {
  CHANGE_API_STEP,
  CHANGE_SEARCH_CRITERIA,
  CHANGE_ITEMS
};
