const UPDATE_PANEL_PROPS = "UPDATE_PANEL_PROPS";
const ADD_PANEL = "ADD_PANEL";
const REMOVE_PANEL = "REMOVE_PANEL";
const CHANGE_STEP = "CHANGE_STEP";

module.exports = {
  UPDATE_PANEL_PROPS,
  ADD_PANEL,
  REMOVE_PANEL,
  CHANGE_STEP
};
