const REMOVE_ASSET_FROM_GALLERY_START = "REMOVE_ASSET_FROM_GALLERY_START";
const REMOVE_ASSET_FROM_GALLERY_SUCCESS = "REMOVE_ASSET_FROM_GALLERY_SUCCESS";
const REMOVE_ASSET_FROM_GALLERY_FAILED = "REMOVE_ASSET_FROM_GALLERY_FAILED";

const UPLOAD_ASSET_START = "UPLOAD_ASSET_START";
const UPLOAD_ASSET_SUCCESS = "UPLOAD_ASSET_SUCCESS";
const UPLOAD_ASSET_FAILED = "UPLOAD_ASSET_FAILED";

const ASSETS_LAYOUT_START = "ASSETS_LAYOUT_START";
const ASSETS_LAYOUT_SUCCESS = "ASSETS_LAYOUT_SUCCESS";
const ASSETS_LAYOUT_FAILED = "ASSETS_LAYOUT_FAILED";
const HIDE_ERROR = "HIDE_ERROR";

module.exports = {
  REMOVE_ASSET_FROM_GALLERY_START,
  REMOVE_ASSET_FROM_GALLERY_SUCCESS,
  REMOVE_ASSET_FROM_GALLERY_FAILED,
  UPLOAD_ASSET_START,
  UPLOAD_ASSET_SUCCESS,
  UPLOAD_ASSET_FAILED,
  ASSETS_LAYOUT_START,
  ASSETS_LAYOUT_SUCCESS,
  ASSETS_LAYOUT_FAILED,
  HIDE_ERROR
};
