const REMOVE_ASSET_FROM_GALLERY = "REMOVE_ASSET_FROM_GALLERY";
const UPLOAD_ASSET_START = "UPLOAD_ASSET_START";
const UPLOAD_ASSET_SUCCESS = "UPLOAD_ASSET_SUCCESS";
const UPLOAD_ASSET_FAILED = "UPLOAD_ASSET_FAILED";

const ASSETS_LAYOUT_START = "ASSETS_LAYOUT_START";
const ASSETS_LAYOUT_SUCCESS = "ASSETS_LAYOUT_SUCCESS";
const ASSETS_LAYOUT_FAILED = "ASSETS_LAYOUT_FAILED";

module.exports = {
  REMOVE_ASSET_FROM_GALLERY,
  UPLOAD_ASSET_START,
  UPLOAD_ASSET_SUCCESS,
  UPLOAD_ASSET_FAILED,
  ASSETS_LAYOUT_START,
  ASSETS_LAYOUT_SUCCESS,
  ASSETS_LAYOUT_FAILED
};
