const UPDATE_LAYOUT_TEMPLATE = "UPDATE_LAYOUT_TEMPLATE";
const SAVE_LAYOUT_TEMPLATE_START = "SAVE_LAYOUT_TEMPLATE_START";
const SAVE_LAYOUT_TEMPLATE_FAILED = "SAVE_LAYOUT_TEMPLATE_FAILED";
const SAVE_LAYOUT_TEMPLATE_SUCCESS = "SAVE_LAYOUT_TEMPLATE_SUCCESS";
const SAVE_ICON_TEMPLATE_START = "SAVE_ICON_TEMPLATE_START";
const SAVE_ICON_TEMPLATE_FAILED = "SAVE_ICON_TEMPLATE_FAILED";
const SAVE_ICON_TEMPLATE_SUCCESS = "SAVE_ICON_TEMPLATE_SUCCESS";

module.exports = {
  UPDATE_LAYOUT_TEMPLATE,
  SAVE_LAYOUT_TEMPLATE_START,
  SAVE_LAYOUT_TEMPLATE_FAILED,
  SAVE_LAYOUT_TEMPLATE_SUCCESS,
  SAVE_ICON_TEMPLATE_START,
  SAVE_ICON_TEMPLATE_FAILED,
  SAVE_ICON_TEMPLATE_SUCCESS
};
