const CALCULATE_PRICE = "CALCULATE_PRICE";
const CALCULATE_PRICE_INITIAL = "CALCULATE_PRICE_INITIAL";
const CHANGE_OPTIONS = "CHANGE_OPTIONS";
module.exports = {
  CALCULATE_PRICE,
  CALCULATE_PRICE_INITIAL,
  CHANGE_OPTIONS
};
