const CALCULATE_PRICE = "CALCULATE_PRICE";
const CALCULATE_PRICE_INITIAL = "CALCULATE_PRICE_INITIAL";
const CHANGE_OPTIONS = "CHANGE_OPTIONS";
const START_CHANGE_PRINT_OPTIONS = "START_CHANGE_PRINT_OPTIONS";
const STOP_CHANGE_PRINT_OPTIONS = "STOP_CHANGE_PRINT_OPTIONS";
module.exports = {
  CALCULATE_PRICE,
  CALCULATE_PRICE_INITIAL,
  CHANGE_OPTIONS,
  START_CHANGE_PRINT_OPTIONS,
  STOP_CHANGE_PRINT_OPTIONS
};
