const CHANGE_PROJECT_TITLE = "CHANGE_PROJECT_TITLE";
const ADD_OBJECT = "ADD_OBJECT";
const ADD_OBJECT_TO_PAGE = "ADD_OBJECT_TO_PAGE";
const ADD_OBJECT_ID_TO_SELECTED = "ADD_OBJECT_ID_TO_SELECTED";
const ADD_OBJECT_ID_ACTION_SELECTED = "ADD_OBJECT_ID_ACTION_SELECTED";
const REMOVE_SELECTION = "REMOVE_SELECTION";
const REMOVE_ACTION_SELECTION = "REMOVE_ACTION_SELECTION";
const UPDATE_OBJECT_PROPS = "UPDATE_OBJECT_PROPS";
const UPDATE_SELECTION_OBJECTS_COORDS = "UPDATE_SELECTION_OBJECTS_COORDS";
const UPDATE_ACTIVE_SELECTION_PROPS = "UPDATE_ACTIVE_SELECTION_PROPS";

const UPDATE_LAYER_PROP = "UPDATE_LAYER_PROP";
const DUPLICATE_OBJ = "DUPLICATE_OBJ";
const DELETE_OBJ = "DELETE_OBJ";
const UPDATE_CROP_PARAMS = "UPDATE_CROP_PARAMS";
const CHANGE_PAGE = "CHANGE_PAGE";
const CHANGE_GROUPS = "CHANGE_GROUPS";
const CHANGE_ZOOM = "CHANGE_ZOOM";

const ON_TEXT_CHANGE = "ON_TEXT_CHANGE";

module.exports = {
  CHANGE_PROJECT_TITLE,
  ADD_OBJECT,
  ADD_OBJECT_TO_PAGE,
  ADD_OBJECT_ID_TO_SELECTED,
  ADD_OBJECT_ID_ACTION_SELECTED,
  UPDATE_OBJECT_PROPS,
  REMOVE_SELECTION,
  REMOVE_ACTION_SELECTION,
  UPDATE_SELECTION_OBJECTS_COORDS,
  UPDATE_ACTIVE_SELECTION_PROPS,
  UPDATE_LAYER_PROP,
  DUPLICATE_OBJ,
  UPDATE_CROP_PARAMS,
  DELETE_OBJ,
  CHANGE_GROUPS,
  CHANGE_PAGE,
  CHANGE_ZOOM,
  ON_TEXT_CHANGE
};
