const CHANGE_PROJECT_TITLE = "CHANGE_PROJECT_TITLE";
const ADD_OBJECT = "ADD_OBJECT";
const ADD_OBJECT_TO_PAGE = "ADD_OBJECT_TO_PAGE";
const ADD_OBJECT_ID_TO_SELECTED = "ADD_OBJECT_ID_TO_SELECTED";
const ADD_OBJECT_ID_ACTION_SELECTED = "ADD_OBJECT_ID_ACTION_SELECTED";
const REMOVE_SELECTION = "REMOVE_SELECTION";
const REMOVE_ACTION_SELECTION = "REMOVE_ACTION_SELECTION";
const UPDATE_OBJECT_PROPS = "UPDATE_OBJECT_PROPS";
const UPDATE_SELECTION_OBJECTS_COORDS = "UPDATE_SELECTION_OBJECTS_COORDS";
const UPDATE_ACTIVE_SELECTION_PROPS = "UPDATE_ACTIVE_SELECTION_PROPS";

const UPDATE_LAYER_PROP = "UPDATE_LAYER_PROP";
const DUPLICATE_OBJ = "DUPLICATE_OBJ";
const DELETE_OBJ = "DELETE_OBJ";
const UPDATE_CROP_PARAMS = "UPDATE_CROP_PARAMS";
const CHANGE_PAGE = "CHANGE_PAGE";
const CHANGE_GROUPS = "CHANGE_GROUPS";
const CHANGE_ZOOM = "CHANGE_ZOOM";

const ON_TEXT_CHANGE = "ON_TEXT_CHANGE";

const PROJ_SAVE_START = "PROJ_SAVE_START";
const PROJ_SAVE_SUCCESS = "PROJ_SAVE_SUCCESS";
const PROJ_SAVE_FAILED = "PROJ_SAVE_FAILED";
const PROJ_SAVE_CLEAR_MESSAGE = "PROJ_SAVE_CLEAR_MESSAGE";

const PROJ_LOAD_START = "PROJ_LOAD_START";
const PROJ_LOAD_SUCCESS = "PROJ_LOAD_SUCCESS";
const PROJ_LOAD_FAILED = "PROJ_LOAD_FAILED";
const PROJ_LOAD_CLEAR_MESSAGE = "PROJ_LOAD_CLEAR_MESSAGE";
const PROJ_LOAD_DELETE_START = "PROJ_LOAD_DELETE_START";
const PROJ_LOAD_DELETE_SUCCESS = "PROJ_LOAD_DELETE_SUCCESS";
const PROJ_LOAD_DELETE_FAILED = "PROJ_LOAD_DELETE_FAILED";
const PROJ_LOAD_DELETE_CLEAR_MESSAGE = "PROJ_LOAD_DELETE_CLEAR_MESSAGE";
const PROJ_LOAD_PROJECT_START = "PROJ_LOAD_PROJECT_START";
const PROJ_LOAD_PROJECT_SUCCESS = "PROJ_LOAD_PROJECT_SUCCESS";
const PROJ_LOAD_PROJECT_FAILED = "PROJ_LOAD_PROJECT_FAILED";
const PROJ_LOAD_PROJECT_CLEAR_MESSAGE = "PROJ_LOAD_PROJECT_CLEAR_MESSAGE";

const CHANGE_RANDOM_PAGE = "CHANGE_RANDOM_PAGE";
const OBJECTS_READY = "OBJECTS_READY";

const PROJ_SHOW_POPUP = "PROJ_SHOW_POPUP";

module.exports = {
  CHANGE_PROJECT_TITLE,
  ADD_OBJECT,
  ADD_OBJECT_TO_PAGE,
  ADD_OBJECT_ID_TO_SELECTED,
  ADD_OBJECT_ID_ACTION_SELECTED,
  UPDATE_OBJECT_PROPS,
  REMOVE_SELECTION,
  REMOVE_ACTION_SELECTION,
  UPDATE_SELECTION_OBJECTS_COORDS,
  UPDATE_ACTIVE_SELECTION_PROPS,
  UPDATE_LAYER_PROP,
  DUPLICATE_OBJ,
  UPDATE_CROP_PARAMS,
  DELETE_OBJ,
  CHANGE_GROUPS,
  CHANGE_PAGE,
  CHANGE_ZOOM,
  ON_TEXT_CHANGE,
  CHANGE_RANDOM_PAGE,
  OBJECTS_READY,
  PROJ_SAVE_START,
  PROJ_SAVE_SUCCESS,
  PROJ_SAVE_FAILED,
  PROJ_SAVE_CLEAR_MESSAGE,
  PROJ_LOAD_START,
  PROJ_LOAD_SUCCESS,
  PROJ_LOAD_FAILED,
  PROJ_LOAD_CLEAR_MESSAGE,
  PROJ_LOAD_DELETE_START,
  PROJ_LOAD_DELETE_SUCCESS,
  PROJ_LOAD_DELETE_FAILED,
  PROJ_LOAD_DELETE_CLEAR_MESSAGE,
  PROJ_LOAD_PROJECT_START,
  PROJ_LOAD_PROJECT_SUCCESS,
  PROJ_LOAD_PROJECT_FAILED,
  PROJ_LOAD_PROJECT_CLEAR_MESSAGE,
  PROJ_SHOW_POPUP
};
