const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const EXPAND_SIDEBAR = "EXPAND_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const ACTIVATE_SIDEBAR = "ACTIVATE_SIDEBAR";
const DEACTIVATE_SIDEBAR = "DEACTIVATE_SIDEBAR";
module.exports = {
  TOGGLE_SIDEBAR,
  EXPAND_SIDEBAR,
  CLOSE_SIDEBAR,
  ACTIVATE_SIDEBAR,
  DEACTIVATE_SIDEBAR
};
