const UI_UPDATE_WORK_AREA_OFFSET_PAGE_OFSSET =
  "UI_UPDATE_WORK_AREA_OFFSET_PAGE_OFSSET";
const UI_UPDATE_CONTAINER_CANVAS_OFFSET = "UI_UPDATE_CONTAINER_CANVAS_OFFSET";
const UI_UPDATE_VIEWPORT_TRANSFORM = "UI_UPDATE_VIEWPORT_TRANSFORM";
const UPDATE_ZOOM = "UPDATE_ZOOM";
const CHANGE_ZOOM = "CHANGE_ZOOM";
const CHANGE_WORKAREA_PROPS = "CHANGE_WORKAREA_PROPS";
const CHANGE_RERENDER_ID = "CHANGE_RERENDER_ID";
const UI_ADD_COLOR = "UI_ADD_COLOR";
const UI_ADD_LAST_USED_COLOR = "UI_ADD_LAST_USED_COLOR";

module.exports = {
  UI_UPDATE_WORK_AREA_OFFSET_PAGE_OFSSET,
  UI_UPDATE_CONTAINER_CANVAS_OFFSET,
  UI_UPDATE_VIEWPORT_TRANSFORM,
  UPDATE_ZOOM,
  CHANGE_ZOOM,
  CHANGE_WORKAREA_PROPS,
  CHANGE_RERENDER_ID,
  UI_ADD_COLOR,
  UI_ADD_LAST_USED_COLOR
};
