const TEST_CHANGE_VARIABLE = "TEST_CHANGE_VARIABLE";
const CHANGE_VARIABLE_VALUE = "CHANGE_VARIABLE_VALUE";
const CHANGE_COLOR_VARIABLE_VALUE = "CHANGE_COLOR_VARIABLE_VALUE";
module.exports = {
  TEST_CHANGE_VARIABLE,
  CHANGE_VARIABLE_VALUE,
  CHANGE_COLOR_VARIABLE_VALUE
};
