const TEST_CHANGE_VARIABLE = "TEST_CHANGE_VARIABLE";
const CHANGE_VARIABLE_VALUE = "CHANGE_VARIABLE_VALUE";
const CHANGE_COLOR_VARIABLE_VALUE = "CHANGE_COLOR_VARIABLE_VALUE";
const UPDATE_OBJ_FROM_VARIABLE = "UPDATE_OBJ_FROM_VARIABLE";
const UPDATE_OBJ_COLOR_FROM_VARIABLE = "UPDATE_OBJ_COLOR_FROM_VARIABLE";
const UPDATE_OBJ_IMAGE_FROM_VARIABLE = "UPDATE_OBJ_IMAGE_FROM_VARIABLE";
const UPDATE_OBJ_FROM_VARIABLE_INIT = "UPDATE_OBJ_FROM_VARIABLE_INIT";
const CHECK_VARIABLE_VALID = "CHECK_VARIABLE_VALID";

module.exports = {
  TEST_CHANGE_VARIABLE,
  CHANGE_VARIABLE_VALUE,
  CHANGE_COLOR_VARIABLE_VALUE,
  UPDATE_OBJ_FROM_VARIABLE,
  CHECK_VARIABLE_VALID,
  UPDATE_OBJ_COLOR_FROM_VARIABLE,
  UPDATE_OBJ_IMAGE_FROM_VARIABLE,
  UPDATE_OBJ_FROM_VARIABLE_INIT
};
