const AUTH_SIGNIN_START = "AUTH_SIGNIN_START";
const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
const AUTH_SIGNIN_FAILED = "AUTH_SIGNIN_FAILED";
const AUTH_SIGNIN_CLEAR_MESSAGE = "AUTH_SIGNIN_CLEAR_MESSAGE";

module.exports = {
  AUTH_SIGNIN_START,
  AUTH_SIGNIN_SUCCESS,
  AUTH_SIGNIN_FAILED,
  AUTH_SIGNIN_CLEAR_MESSAGE
};
