const REMOVE_IMAGE_FROM_GALLERY = "REMOVE_IMAGE_FROM_GALLERY";
const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";

module.exports = {
  REMOVE_IMAGE_FROM_GALLERY,
  UPLOAD_IMAGE_START,
  UPLOAD_IMAGE_SUCCESS,
  UPLOAD_IMAGE_FAILED
};
