const Position = {
  TOP: "top",
  BOTTOM: "bottom",
  OTHER: "other",
  HIDDEN: "hidden"
};

const BUTTON = "BUTTON";
const POPTEXT_ICON = "POPTEXT_ICON";
const POPTEXT_VALUE = "POPTEXT_VALUE";
const INCREMENTAL = "INCREMENTAL";
const SLIDER = "SLIDER";
const COLOR_TAB_COLOR_CHOOSER = "COLOR_TAB_COLOR_CHOOSER";
const COLOR_TAB_WIDTH_CHOOSER = "COLOR_TAB_WIDTH_CHOOSER";

const BUTTON_LETTER_BOLD = "BUTTON_LETTER_BOLD";
const BUTTON_LETTER_ITALIC = "BUTTON_LETTER_ITALIC";
const BUTTON_LETTER_UNDERLINE = "BUTTON_LETTER_UNDERLINE";

const BUTTON_LEFT_ALIGNED = "BUTTON_LEFT_ALIGNED";
const BUTTON_RIGHT_ALIGNED = "BUTTON_RIGHT_ALIGNED";
const BUTTON_CENTER_ALIGNED = "BUTTON_CENTER_ALIGNED";
const BUTTON_JUSTIFY_ALIGNED = "BUTTON_JUSTIFY_ALIGNED";
const BUTTON_DUPLICATE = "BUTTON_DUPLICATE";

const POPTEXT_MENU = "POPTEXT_MENU";
const POPTEXT_LAYER = "POPTEXT_LAYER";
const POPTEXT_VALIGN = "POPTEXT_VALIGN";
const POPTEXT_FONT = "POPTEXT_FONT";
const POPTEXT_IMAGE_MENU = "POPTEXT_IMAGE_MENU";

const POPTEXT_IMAGE_SHAPE_MENU = "POPTEXT_IMAGE_SHAPE_MENU";

const SLIDER_TEXT_SPACEING = "SLIDER_TEXT_SPACEING";
const SLIDER_WND = "SLIDER_WND";
const SLIDER_OPACITY_WND = "SLIDER_OPACITY_WND";
const SLIDER_FONT_WND = "SLIDER_FONT_WND";

const SLIDER_INLINE = "SLIDER_INLINE";

const INCREMENTAL_FONT_SIZE = "INCREMENTAL_FONT_SIZE";

const COLOR_SELECTOR = "COLOR_SELECTOR";
const COLOR_SELECTOR_BACKGROUND = "COLOR_SELECTOR_BACKGROUND";

const COLOR_SELECTOR_WND = "COLOR_SELECTOR_WND";

const COLOR = "COLOR";
const COLOR_TAB_FG = "COLOR_TAB_FG";
const COLOR_TAB_BG = "COLOR_TAB_BG";
const COLOR_TAB_BORDER_WIDTH = "COLOR_TAB_BORDER_WIDTH";
const COLOR_TAB_BORDER_COLOR = "COLOR_TAB_BORDER_COLOR";

const SIMPLE_ICON = "SIMPLE_ICON";
const BUTTON_CHANGE_IMAGE = "BUTTON_CHANGE_IMAGE";
const BUTTON_CHANGE_SHAPE = "BUTTON_CHANGE_SHAPE";

const SPECIAL_EFFECTS_WND = "SPECIAL_EFFECTS_WND";
const CHANGE_SHAPE_WND = "CHANGE_SHAPE_WND";
const GALLERY_PREVIEW_WND = "GALLERY_PREVIEW_WND";

const SLIDER_INLINE_IMAGE = "SLIDER_INLINE_IMAGE";
const SIMPLE_ICON_QUALITY = "SIMPLE_ICON_QUALITY";
const FILTER_CHOOSER = "FILTER_CHOOSER";
const FLIP_CHOOSER = "FLIP_CHOOSER";

const REFRESH_TABLE = "REFRESH_TABLE";
const SIMPLE_TEXT = "SIMPLE_TEXT";
const FUPA_SIMPLE_IMAGE = "FUPA_SIMPLE_IMAGE";
const FUPA_TEXT = "FUPA_TEXT";
const FUPA_DOWN_ARROW = "FUPA_DOWN_ARROW";

module.exports = {
  Position,
  BUTTON,
  POPTEXT_ICON,
  POPTEXT_VALUE,
  INCREMENTAL,
  SLIDER,
  COLOR_TAB_COLOR_CHOOSER,
  COLOR_TAB_WIDTH_CHOOSER,
  BUTTON_LETTER_BOLD,
  BUTTON_LETTER_ITALIC,
  BUTTON_LETTER_UNDERLINE,
  BUTTON_LEFT_ALIGNED,
  BUTTON_RIGHT_ALIGNED,
  BUTTON_CENTER_ALIGNED,
  BUTTON_JUSTIFY_ALIGNED,
  BUTTON_DUPLICATE,
  POPTEXT_MENU,
  POPTEXT_LAYER,
  POPTEXT_VALIGN,
  POPTEXT_FONT,
  POPTEXT_IMAGE_MENU,
  POPTEXT_IMAGE_SHAPE_MENU,
  SLIDER_TEXT_SPACEING,
  SLIDER_WND,
  SLIDER_OPACITY_WND,
  SLIDER_FONT_WND,
  SLIDER_INLINE,
  INCREMENTAL_FONT_SIZE,
  COLOR_SELECTOR,
  COLOR_SELECTOR_BACKGROUND,
  COLOR_SELECTOR_WND,
  COLOR,
  COLOR_TAB_FG,
  COLOR_TAB_BG,
  COLOR_TAB_BORDER_WIDTH,
  COLOR_TAB_BORDER_COLOR,
  SIMPLE_ICON,
  BUTTON_CHANGE_IMAGE,
  BUTTON_CHANGE_SHAPE,
  SPECIAL_EFFECTS_WND,
  CHANGE_SHAPE_WND,
  SLIDER_INLINE_IMAGE,
  SIMPLE_ICON_QUALITY,
  FILTER_CHOOSER,
  FLIP_CHOOSER,
  GALLERY_PREVIEW_WND,
  REFRESH_TABLE,
  SIMPLE_TEXT,
  FUPA_SIMPLE_IMAGE,
  FUPA_TEXT,
  FUPA_DOWN_ARROW
};
