const PREVIEW_LOAD_PAGE = "PREVIEW_LOAD_PAGE";
const PREVIEW_GET_PAGE = "PREVIEW_GET_PAGE";
const PREVIEW_LOAD_PAGE_FAILED = "PREVIEW_LOAD_PAGE_FAILED";
const PREVIEW_LOAD_PAGE_SUCCESS = "PREVIEW_LOAD_PAGE_SUCCESS";
const PREVIEW_DISABLE_MODE = "PREVIEW_DISABLE_MODE";
const ATTACH_PREVIEW = "ATTACH_PREVIEW";

module.exports = {
  PREVIEW_LOAD_PAGE,
  PREVIEW_GET_PAGE,
  PREVIEW_LOAD_PAGE_FAILED,
  PREVIEW_LOAD_PAGE_SUCCESS,
  PREVIEW_DISABLE_MODE,
  ATTACH_PREVIEW
};
