const PREVIEW_LOAD_PAGE = "PREVIEW_LOAD_PAGE";
const PREVIEW_GET_PAGE = "PREVIEW_GET_PAGE";
const PREVIEW_LOAD_PAGE_FAILED = "PREVIEW_LOAD_PAGE_FAILED";
const PREVIEW_LOAD_PAGE_SUCCESS = "PREVIEW_LOAD_PAGE_SUCCESS";
const PREVIEW_DISABLE_MODE = "PREVIEW_DISABLE_MODE";

module.exports = {
  PREVIEW_LOAD_PAGE,
  PREVIEW_GET_PAGE,
  PREVIEW_LOAD_PAGE_FAILED,
  PREVIEW_LOAD_PAGE_SUCCESS,
  PREVIEW_DISABLE_MODE
};
