const DAG_UPLOAD_IMAGE = "DAG_UPLOAD_IMAGE";
const DAG_UPLOAD_IMAGE_SUCCESS = "DAG_UPLOAD_IMAGE_SUCCESS";
const DAG_UPLOAD_IMAGE_FAILED = "DAG_UPLOAD_IMAGE_FAILED";
const DAG_CHANGE_SLIDER = "DAG_CHANGE_SLIDER";
const DAG_CHANGE_ACTIVE_COLOR_SCHEMA = "DAG_CHANGE_ACTIVE_COLOR_SCHEMA";
const DAG_CHANGE_COLOR_PICKER = "DAG_CHANGE_COLOR_PICKER";
const DAG_CHANGE_INPUT = "DAG_CHANGE_INPUT";

const DAG_SIGNIN_START = "DAG_SIGNIN_START";
const DAG_SIGNIN_SUCCESS = "DAG_SIGNIN_SUCCESS";
const DAG_SIGNIN_FAILED = "DAG_SIGNIN_FAILED";
const DAG_SIGNIN_CLEAR_MESSAGE = "DAG_SIGNIN_CLEAR_MESSAGE";

module.exports = {
  DAG_UPLOAD_IMAGE,
  DAG_UPLOAD_IMAGE_SUCCESS,
  DAG_UPLOAD_IMAGE_FAILED,
  DAG_CHANGE_SLIDER,
  DAG_CHANGE_ACTIVE_COLOR_SCHEMA,
  DAG_CHANGE_COLOR_PICKER,
  DAG_CHANGE_INPUT,
  DAG_SIGNIN_START,
  DAG_SIGNIN_SUCCESS,
  DAG_SIGNIN_FAILED,
  DAG_SIGNIN_CLEAR_MESSAGE
};
