const REMOVE_PDF_FROM_GALLERY = "REMOVE_PDF_FROM_GALLERY";
const UPLOAD_PDF_START = "UPLOAD_PDF_START";
const UPLOAD_PDF_SUCCESS = "UPLOAD_PDF_SUCCESS";
const UPLOAD_PDF_FAILED = "UPLOAD_PDF_FAILED";

module.exports = {
  REMOVE_PDF_FROM_GALLERY,
  UPLOAD_PDF_START,
  UPLOAD_PDF_SUCCESS,
  UPLOAD_PDF_FAILED
};
